version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "csgy9223a-hw2-photo-stack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-qb9919q2gtn4"
s3_prefix = "csgy9223a-hw2-photo-stack"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
parameter_overrides = "VPCSecurityGroup=\"sg-036e720631eabe997\" VPCSubnet=\"subnet-07e49d6e243a9d766\" OpenSearchUser=\"opens_master\" OpenSearchPassword=\"dM8TMbvsYRPxI$5*WlxNbnD9SULPzmFJ\""
image_repositories = []
