AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: CloudFormation stack for the Intelligent Photo Album

# Globals:
  # TODO

Parameters:
  VPCSecurityGroup:
    Type: String
  VPCSubnetPrivate:
    Type: String
  VPCSubnetOpen:
    Type: String
  # VPCId:
  #   Type: String
  # VPCRouteTable:
  #   Type: String
  OpenSearchUser:
    Type: String
  OpenSearchPassword:
    Type: String


Resources:
  # S3 Bucket#############################################################################
  ImagesBucket:
    Type: 'AWS::S3::Bucket'        


  # Lambdas ################################################################################
  PhotoIndexLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Runtime: python3.9
      CodeUri: src/lambdas/PhotoIndexLambda/
      Handler: lambda_function.lambda_handler
      Description: A lambda function to index photos uploaded to our s3 bucket in OpenSearch
      MemorySize: 256
      Timeout: 120
      Role: !GetAtt TextRecognitionLambdaRole.Arn
      VpcConfig:
        SecurityGroupIds:
          - !Ref VPCSecurityGroup
        SubnetIds:
          - !Ref VPCSubnetPrivate
          - !Ref VPCSubnetOpen
      Events:
        S3Event:
          Type: S3
          Properties:
            Bucket: !Ref ImagesBucket
            Events: s3:ObjectCreated:Put
      Environment:
        Variables:
          OpenSearch_User: !Ref OpenSearchUser
          OpenSearch_Passwored: !Ref OpenSearchPassword



  # Roles ###################################################################################
  # Role for Lambda
  TextRecognitionLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
                - s3.amazonaws.com
                - rekognition.amazonaws.com
        Version: '2012-10-17'
      Path: /
      Policies:
        - PolicyDocument:
            Statement:
              - Action:
                  - logs:CreateLogGroup
                  - logs:DescribeLogGroups
                  - logs:CreateLogStream
                  - logs:DescribeLogStreams
                  - logs:PutLogEvents
                Effect: Allow
                Resource:
                  - !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:*'
              - Action:
                  - 's3:GetObject'
                Effect: Allow
                Resource: 'arn:aws:s3:::*'
              - Action:
                  - rekognition:*
                Effect: Allow
                Resource: "*"
              - Action:
                  - ec2:CreateNetworkInterface
                  - ec2:DescribeNetworkInterfaces
                  - ec2:DeleteNetworkInterface
                  - ec2:DescribeInstances
                  - ec2:AttachNetworkInterface
                Effect: Allow
                Resource: "*"
            Version: '2012-10-17'
          PolicyName: TextRecognitionLambdaPolicy
      RoleName: TextRecognitionLambdaRole


# PERMISSIONS ################################################################3333#######
  InvokeLambdaPermission:
    Type: "AWS::Lambda::Permission"
    Properties:
      FunctionName: !GetAtt PhotoIndexLambda.Arn
      Action: lambda:InvokeFunction
      Principal: s3.amazonaws.com
      SourceArn: !GetAtt ImagesBucket.Arn


# VPC Endpoints
  RekognitionVpcEndpoint:
    Type: "AWS::EC2::VPCEndpoint"
    Properties:
      PrivateDnsEnabled: True
      SecurityGroupIds:
        - !Ref VPCSecurityGroup
      SubnetIds:
        - !Ref VPCSubnetPrivate
      ServiceName: com.amazonaws.us-east-1.rekognition
      VpcEndpointType: Interface
      VpcId: "vpc-06dddc2a059e86959"




# Outputs:
  # TODO