AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: CloudFormation stack for the Intelligent Photo Album

# Globals:
  # TODO

Parameters:
  VPCSecurityGroup:
    Type: String
  VPCSubnet:
    Type: String
  VPCRoutingTable:
    Type: String
  VpcId:
    Type: String


Resources:
  # S3 Bucket#############################################################################
  ImagesBucket:
    Type: 'AWS::S3::Bucket'
    # Properties:
    #   NotificationConfiguration:
    #     LambdaConfigurations:
    #       - Event: s3:ObjectCreated:Put
    #         Function: !GetAtt PhotoIndexLambda.Arn

  # S3VpcAccessPoint:
  #   Type: 'AWS::S3::AccessPoint'
  #   Properties:
  #     Bucket: !Ref ImagesBucket
  # S3GatewayEndpoint:
  #   Type: AWS::EC2::VPCEndpoint
  #   Properties:
  #     PolicyDocument:
  #       Version: 2012-10-17
  #       Statement:
  #         - Effect: Allow
  #           Principal: "*"
  #           Action:
  #             - s3:GetObject
  #           Resource: !GetAtt ImagesBucket.Arn
  #     RouteTableIds:
  #       - !Ref VPCRoutingTable
  #     ServiceName: !Sub 'com.amazonaws.${AWS::Region}.s3'
  #     VpcId: !Ref VpcId


        


  # Lambdas ################################################################################
  PhotoIndexLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Runtime: python3.9
      CodeUri: src/lambdas/PhotoIndexLambda/
      Handler: lambda_function.lambda_handler
      Description: A lambda function to index photos uploaded to our s3 bucket in OpenSearch
      MemorySize: 128
      Timeout: 30
      Role: !GetAtt TextRecognitionLambdaRole.Arn
      VpcConfig:
        SecurityGroupIds:
          - !Ref VPCSecurityGroup
        SubnetIds:
          - !Ref VPCSubnet
      Events:
        S3Event:
          Type: S3
          Properties:
            Bucket: !Ref ImagesBucket
            Events: s3:ObjectCreated:Put


  # Roles ###################################################################################
  # Role for Lambda
  TextRecognitionLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
                - s3.amazonaws.com
        Version: '2012-10-17'
      Path: /
      Policies:
        - PolicyDocument:
            Statement:
              - Action:
                  - logs:CreateLogGroup
                  - logs:DescribeLogGroups
                  - logs:CreateLogStream
                  - logs:DescribeLogStreams
                  - logs:PutLogEvents
                Effect: Allow
                Resource:
                  - !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:*'
              - Action:
                  - 's3:GetObject'
                Effect: Allow
                Resource: 'arn:aws:s3:::*'
              - Action:
                  - rekognition:DetectText
                Effect: Allow
                Resource: "*"
              - Action:
                  - ec2:CreateNetworkInterface
                  - ec2:DescribeNetworkInterfaces
                  - ec2:DeleteNetworkInterface
                  - ec2:DescribeInstances
                  - ec2:AttachNetworkInterface
                Effect: Allow
                Resource: "*"
            Version: '2012-10-17'
          PolicyName: TextRecognitionLambdaPolicy
      RoleName: TextRecognitionLambdaRole

  InvokeLambdaPermission:
    Type: "AWS::Lambda::Permission"
    Properties:
      FunctionName: !GetAtt PhotoIndexLambda.Arn
      Action: lambda:InvokeFunction
      Principal: s3.amazonaws.com
      SourceArn: !GetAtt ImagesBucket.Arn



# Outputs:
  # TODO