AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: CloudFormation stack for the Intelligent Photo Album

# Globals:
  # TODO

Parameters:
  VPCSecurityGroup:
    Type: String
  VPCSubnet:
    Type: String
    

# Resources:
  # TODO

# Outputs:
  # TODO