AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: CloudFormation stack for the Intelligent Photo Album

# Globals:
  # TODO

Parameters:
  VPCSecurityGroup:
    Type: String
  VPCSubnet:
    Type: String


Resources:
  # S3 Bucket
  ImagesBucket:
    Type: 'AWS::S3::Bucket'
    


  # Lambdas
  PhotoIndexLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Runtime: python3.9
      CodeUri: src/lambdas/PhotoIndexLambda/
      Handler: lambda_function.lambda_handler
      Description: A lambda function to index photos uploaded to our s3 bucket in OpenSearch
      MemorySize: 128
      Timeout: 30
      VpcConfig:
        SecurityGroupIds:
          - !Ref VPCSecurigyGroup
        SubnetIds:
          - !Ref VPCSubnet


# Outputs:
  # TODO